/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_getHello"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all chats for the current user */
        get: operations["ChatsController_getChats"];
        put?: never;
        /** Create a new chat */
        post: operations["ChatsController_createChat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chats/{chatId}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get paginated messages for a chat */
        get: operations["ChatsController_getMessages"];
        put?: never;
        /** Send a message to a chat */
        post: operations["ChatsController_sendMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chats/{chatId}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a member to a chat */
        post: operations["ChatsController_addMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LastMessageDto: {
            /**
             * Format: uuid
             * @description Unique ID of the message.
             * @example a1b2c3d4-e5f6-7890-abcd-ef1234567890
             */
            id: string;
            /**
             * @description ID of the user who sent the message.
             * @example 42
             */
            senderId: number;
            /**
             * @description Type of the message.
             * @example text
             * @enum {string}
             */
            type: "text" | "system";
            /**
             * @description Message content.
             * @example Hello, world!
             */
            content: string;
            /**
             * Format: date-time
             * @description When the message was sent.
             * @example 2024-01-15T10:30:00.000Z
             */
            createdAt: string;
        };
        ChatMemberDto: {
            /**
             * @description ID of the user.
             * @example 42
             */
            userId: number;
            /**
             * @description Username of the user.
             * @example john_doe
             */
            username: string;
            /**
             * @description Profile picture URL. Currently not provided by the Users API.
             * @example
             */
            imgSrc: string;
        };
        ChatListItemDto: {
            /**
             * Format: uuid
             * @description Unique ID of the chat.
             * @example a1b2c3d4-e5f6-7890-abcd-ef1234567890
             */
            id: string;
            /**
             * @description Display name of the chat. Absent for direct messages.
             * @example Team Chat
             */
            name?: string;
            /** @description Most recent message in the chat. Absent if no messages yet. */
            lastMessage?: components["schemas"]["LastMessageDto"];
            /**
             * @description Number of unread messages for the current user.
             * @example 3
             */
            unreadCount: number;
            /** @description Members of the chat. */
            members: components["schemas"]["ChatMemberDto"][];
        };
        MessageDto: {
            /**
             * Format: uuid
             * @description Unique ID of the message.
             * @example a1b2c3d4-e5f6-7890-abcd-ef1234567890
             */
            id: string;
            /**
             * @description ID of the user who sent the message.
             * @example 42
             */
            senderId: number;
            /**
             * @description Type of the message.
             * @example text
             * @enum {string}
             */
            type: "text" | "system";
            /**
             * @description Text or URL content of the message.
             * @example Hello, world!
             */
            content: string;
            /**
             * Format: date-time
             * @description When the message was sent.
             * @example 2024-01-15T10:30:00.000Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description When the message was last edited. Absent if never edited.
             * @example 2024-01-15T11:00:00.000Z
             */
            editedAt?: string;
            /**
             * @description Whether the message has been soft-deleted. Content will be empty when true.
             * @example false
             */
            isDeleted: boolean;
        };
        PaginatedMessagesDto: {
            /** @description Ordered list of messages, newest first. */
            messages: components["schemas"]["MessageDto"][];
            /**
             * Format: uuid
             * @description Pass as `before` in the next request to fetch the next page. Absent when hasMore is false.
             * @example a1b2c3d4-e5f6-7890-abcd-ef1234567890
             */
            nextCursor?: string;
            /**
             * @description Whether more messages exist before the current page.
             * @example true
             */
            hasMore: boolean;
        };
        CreateMessageDto: {
            /**
             * @description Text or URL content of the message.
             * @example Hello, world!
             */
            content: string;
            /**
             * @description Message type. Defaults to text.
             * @example text
             * @enum {string}
             */
            type?: "text" | "system";
        };
        AddMemberDto: {
            /**
             * @description ID of the user to add to the chat.
             * @example 42
             */
            userId: number;
        };
        CreateChatDto: {
            /**
             * @description Display name of the chat. Omit for direct messages.
             * @example Team Chat
             */
            name?: string;
            /**
             * @description IDs of the users to add as members. The creator is added automatically.
             * @example [
             *       1,
             *       2,
             *       3
             *     ]
             */
            memberIds: number[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_getHello: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ChatsController_getChats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatListItemDto"][];
                };
            };
        };
    };
    ChatsController_createChat: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateChatDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatListItemDto"];
                };
            };
        };
    };
    ChatsController_getMessages: {
        parameters: {
            query?: {
                /** @description Fetch messages older than this message ID. Use the nextCursor from a previous response to paginate. */
                before?: string;
                /** @description Number of messages to return per page. */
                limit?: number;
            };
            header?: never;
            path: {
                chatId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedMessagesDto"];
                };
            };
        };
    };
    ChatsController_sendMessage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chatId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMessageDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageDto"];
                };
            };
        };
    };
    ChatsController_addMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chatId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddMemberDto"];
            };
        };
        responses: {
            /** @description Member added successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
