import { Post } from "../types/Post";
import { Comment } from "../types/Comment";

const sampleComments = {
	post1: [
		{
			commentId: 101,
			userId: 11,
			username: "maria.p",
			userProfilePictureUrl: "https://i.pravatar.cc/150?img=11",
			text: "This color palette is so clean.",
			likes: 8,
			timestamp: "2m ago",
		},
		{
			commentId: 102,
			userId: 12,
			username: "devin_88",
			userProfilePictureUrl: "https://i.pravatar.cc/150?img=12",
			text: "The composition works really well here.",
			likes: 5,
			timestamp: "6m ago",
		},
		{
			commentId: 103,
			userId: 13,
			username: "lauren.s",
			userProfilePictureUrl: "https://i.pravatar.cc/150?img=13",
			text: "Need this on my mood board.",
			likes: 12,
			timestamp: "11m ago",
		},
	] satisfies Comment[],
	post2: [
		{
			commentId: 201,
			userId: 14,
			username: "chriscode",
			userProfilePictureUrl: "https://i.pravatar.cc/150?img=14",
			text: "lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus, doloremque. lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus, doloremque.",
			likes: 3,
			timestamp: "4m ago",
		},
		{
			commentId: 202,
			userId: 15,
			username: "nina.design",
			userProfilePictureUrl: "https://i.pravatar.cc/150?img=15",
			text: "The framing makes it feel cinematic.",
			likes: 9,
			timestamp: "9m ago",
		},
		{
			commentId: 203,
			userId: 16,
			username: "omar_kt",
			userProfilePictureUrl: "https://i.pravatar.cc/150?img=16",
			text: "Nice depth and contrast.",
			likes: 4,
			timestamp: "14m ago",
		},
		{
			commentId: 204,
			userId: 17,
			username: "tessh",
			userProfilePictureUrl: "https://i.pravatar.cc/150?img=17",
			text: "Very polished result.",
			likes: 6,
			timestamp: "18m ago",
		},
        {
			commentId: 201,
			userId: 14,
			username: "chriscode",
			userProfilePictureUrl: "https://i.pravatar.cc/150?img=14",
			text: "lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus, doloremque. lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus, doloremque.",
			likes: 3,
			timestamp: "4m ago",
		},
		{
			commentId: 202,
			userId: 15,
			username: "nina.design",
			userProfilePictureUrl: "https://i.pravatar.cc/150?img=15",
			text: "The framing makes it feel cinematic.",
			likes: 9,
			timestamp: "9m ago",
		},
		{
			commentId: 203,
			userId: 16,
			username: "omar_kt",
			userProfilePictureUrl: "https://i.pravatar.cc/150?img=16",
			text: "Nice depth and contrast.",
			likes: 4,
			timestamp: "14m ago",
		},
		{
			commentId: 204,
			userId: 17,
			username: "tessh",
			userProfilePictureUrl: "https://i.pravatar.cc/150?img=17",
			text: "Very polished result.",
			likes: 6,
			timestamp: "18m ago",
		},
	] satisfies Comment[],
	post3: [
		{
			commentId: 301,
			userId: 18,
			username: "ryan.l",
			userProfilePictureUrl: "https://i.pravatar.cc/150?img=18",
			text: "This looks super intentional.",
			likes: 7,
			timestamp: "1m ago",
		},
		{
			commentId: 302,
			userId: 19,
			username: "alexis.m",
			userProfilePictureUrl: "https://i.pravatar.cc/150?img=19",
			text: "Great perspective choice.",
			likes: 2,
			timestamp: "5m ago",
		},
		{
			commentId: 303,
			userId: 20,
			username: "sammyv",
			userProfilePictureUrl: "https://i.pravatar.cc/150?img=20",
			text: "I like how balanced this feels.",
			likes: 10,
			timestamp: "13m ago",
		},
		{
			commentId: 304,
			userId: 21,
			username: "jules_n",
			userProfilePictureUrl: "https://i.pravatar.cc/150?img=21",
			text: "Clean UI energy.",
			likes: 4,
			timestamp: "21m ago",
		},
		{
			commentId: 305,
			userId: 22,
			username: "kevinz",
			userProfilePictureUrl: "https://i.pravatar.cc/150?img=22",
			text: "This one stands out.",
			likes: 11,
			timestamp: "25m ago",
		},
	] satisfies Comment[],
	post4: [
		{
			commentId: 401,
			userId: 23,
			username: "aya.studio",
			userProfilePictureUrl: "https://i.pravatar.cc/150?img=23",
			text: "The detail work is excellent.",
			likes: 14,
			timestamp: "3m ago",
		},
		{
			commentId: 402,
			userId: 24,
			username: "mike.dev",
			userProfilePictureUrl: "https://i.pravatar.cc/150?img=24",
			text: "Really strong visual hierarchy.",
			likes: 5,
			timestamp: "8m ago",
		},
		{
			commentId: 403,
			userId: 25,
			username: "frankie.a",
			userProfilePictureUrl: "https://i.pravatar.cc/150?img=25",
			text: "This would convert well in an app.",
			likes: 6,
			timestamp: "16m ago",
		},
	] satisfies Comment[],
	post5: [
		{
			commentId: 501,
			userId: 26,
			username: "sophia.r",
			userProfilePictureUrl: "https://i.pravatar.cc/150?img=26",
			text: "That spacing is satisfying.",
			likes: 13,
			timestamp: "2m ago",
		},
		{
			commentId: 502,
			userId: 27,
			username: "eliot.h",
			userProfilePictureUrl: "https://i.pravatar.cc/150?img=27",
			text: "Nice work keeping it minimal.",
			likes: 4,
			timestamp: "10m ago",
		},
		{
			commentId: 503,
			userId: 28,
			username: "peterq",
			userProfilePictureUrl: "https://i.pravatar.cc/150?img=28",
			text: "The colors feel cohesive.",
			likes: 9,
			timestamp: "15m ago",
		},
		{
			commentId: 504,
			userId: 29,
			username: "lena.w",
			userProfilePictureUrl: "https://i.pravatar.cc/150?img=29",
			text: "This has a great feed presence.",
			likes: 8,
			timestamp: "19m ago",
		},
	] satisfies Comment[],
} as const;

export const postsSampleData: Post[] = [
	{
		postId: 1,
		userId: 1,
		username: "design.daily",
		userProfilePictureUrl: "https://i.pravatar.cc/150?img=1",
		imgUrl: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=1200&q=80",
		caption: "Building interfaces that feel calm, clear, and fast.",
		likes: 128,
		comments: sampleComments.post1,
	},
	{
		postId: 2,
		userId: 2,
		username: "pixel.pulse",
		userProfilePictureUrl: "https://i.pravatar.cc/150?img=2",
		imgUrl: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1200&q=80",
		caption: "A small UI detail can change the whole feel of a screen.",
		likes: 94,
		comments: sampleComments.post2,
	},
	{
		postId: 3,
		userId: 3,
		username: "studio.notes",
		userProfilePictureUrl: "https://i.pravatar.cc/150?img=3",
		imgUrl: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=1200&q=80",
		caption: "Working through layout choices one layer at a time.",
		likes: 201,
		comments: sampleComments.post3,
	},
	{
		postId: 4,
		userId: 4,
		username: "frontend.foundry",
		userProfilePictureUrl: "https://i.pravatar.cc/150?img=4",
		imgUrl: "https://images.unsplash.com/photo-1487058792275-0ad4aaf24ca7?auto=format&fit=crop&w=1200&q=80",
		caption: "Keeping the structure simple makes the details matter more.",
		likes: 76,
		comments: sampleComments.post4,
	},
	{
		postId: 5,
		userId: 5,
		username: "interface.hub",
		userProfilePictureUrl: "https://i.pravatar.cc/150?img=5",
		imgUrl: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80",
		caption: "A feed card should be readable at a glance.",
		likes: 143,
		comments: sampleComments.post5,
	},
];

export default postsSampleData;